sudo: required
language: clojure
services:
- docker
before_install:
- docker build -f Dockerfile -t tumtum .
- docker run -d tumtum
- docker ps -a
- docker run tumtum /bin/sh -c "lein test"
script:
- lein test
