version: "3.3"
services:

  tumtum_db:
    image: tumtum_db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 15444:5432
    volumes:
       - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    image: tumtum
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build: "min"
    depends_on:
      - tumtum_db
    command:
      ["lein", "run", "prod"]
    ports:
      - 8081:8080

volumes:
  pgdata:
    external:
      name: pgdata
